# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  
  pod 'NVActivityIndicatorView'

  # Pods for My Chat

  target 'My ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My ChatUITests' do
    # Pods for testing
  end

  pod 'MaterialComponents', '~> 81.1.0'
  
end
